# Generated by Django 3.1.4 on 2020-12-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0004_auto_20201229_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1),
        ),
    ]
