# Generated by Django 3.1.4 on 2020-12-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0007_auto_20201229_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
        ),
    ]
