name: integracion continua

on:
  push:
    branches:
      - develop 

jobs:
  ci_to_master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@develop
      - name: Pull
        run: echo 'hola'
